# Generated by Django 3.0.5 on 2020-06-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostessprofile',
            name='rank',
            field=models.CharField(choices=[('SR', 'シルバー'), ('GD', 'ゴールド'), ('PM', 'プラチナ')], db_index=True, default='SR', max_length=2, verbose_name='rank'),
        ),
    ]
