# Generated by Django 3.0.5 on 2020-06-27 08:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_hostessprofile_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostessprofile',
            name='birthday',
        ),
        migrations.AddField(
            model_name='hostessprofile',
            name='age',
            field=models.IntegerField(default=None, null=True, verbose_name='age'),
        ),
        migrations.AddField(
            model_name='hostessprofile',
            name='area',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('kabuki', '歌舞伎町'), ('roppongi', '六本木'), ('ginza', '銀座'), ('shibuya', '渋谷'), ('kitashinchi', '北新地'), ('minami', 'ミナミ'), ('other', 'その他')], db_index=True, max_length=20, verbose_name='area'), default=list, size=10),
        ),
        migrations.AddField(
            model_name='hostessprofile',
            name='body',
            field=models.CharField(choices=[('slim', 'スリム'), ('semi-slim', 'やや細目'), ('normal', '普通'), ('glamorous', 'グラマー'), ('musclar', '筋肉質'), ('semi-fat', 'ややぽっちゃり'), ('fat', '太め')], db_index=True, default=None, max_length=20, null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='hostessprofile',
            name='message',
            field=models.TextField(default=None, null=True, verbose_name='message'),
        ),
        migrations.AddField(
            model_name='hostessprofile',
            name='personality',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('heal', '癒し'), ('goody', '天然'), ('evil', '小悪魔'), ('pure', 'ピュア/素直'), ('smart', '知的'), ('groovy', 'ノリノリ'), ('friendly', 'フレンドリー'), ('outdoor', 'アウトドア'), ('indoor', 'インドア')], db_index=True, max_length=20, verbose_name='personality'), default=list, size=10),
        ),
        migrations.AddField(
            model_name='hostessprofile',
            name='style',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('celeb', 'お姉さん・セレブ'), ('sexy', 'セクシー・ナイスバディ'), ('slim', 'モデル・スレンダー'), ('business', 'ビジネスパーソン'), ('young', 'ロリータ・妹'), ('school', '女子大生'), ('girl', 'ギャル'), ('fat', 'ぽっちゃり')], db_index=True, max_length=20, verbose_name='style'), default=list, size=10),
        ),
    ]
