# Generated by Django 3.0.5 on 2020-06-27 12:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200627_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostessprofile',
            name='area',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('kabuki', '歌舞伎町'), ('roppongi', '六本木'), ('ginza', '銀座'), ('shibuya', '渋谷'), ('kitashinchi', '北新地'), ('minami', 'ミナミ'), ('other', 'その他')], max_length=20), blank=True, db_index=True, default=list, size=10),
        ),
        migrations.AlterField(
            model_name='hostessprofile',
            name='body',
            field=models.CharField(blank=True, choices=[('slim', 'スリム'), ('semi-slim', 'やや細目'), ('normal', '普通'), ('glamorous', 'グラマー'), ('musclar', '筋肉質'), ('semi-fat', 'ややぽっちゃり'), ('fat', '太め')], db_index=True, default=None, max_length=20, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='hostessprofile',
            name='height',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True, verbose_name='height'),
        ),
        migrations.AlterField(
            model_name='hostessprofile',
            name='image',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=1024), default=list, size=10),
        ),
        migrations.AlterField(
            model_name='hostessprofile',
            name='personality',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('heal', '癒し'), ('goody', '天然'), ('evil', '小悪魔'), ('pure', 'ピュア/素直'), ('smart', '知的'), ('groovy', 'ノリノリ'), ('friendly', 'フレンドリー'), ('outdoor', 'アウトドア'), ('indoor', 'インドア')], max_length=20), blank=True, db_index=True, default=list, size=10),
        ),
        migrations.AlterField(
            model_name='hostessprofile',
            name='style',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('celeb', 'お姉さん・セレブ'), ('sexy', 'セクシー・ナイスバディ'), ('slim', 'モデル・スレンダー'), ('business', 'ビジネスパーソン'), ('young', 'ロリータ・妹'), ('school', '女子大生'), ('girl', 'ギャル'), ('fat', 'ぽっちゃり')], max_length=20), blank=True, db_index=True, default=list, size=10),
        ),
    ]
