# Generated by Django 3.0.5 on 2020-06-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200627_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostessprofile',
            old_name='image',
            new_name='images',
        ),
    ]
