# Generated by Django 3.0.5 on 2020-07-02 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200627_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='group',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='hostes',
        ),
        migrations.DeleteModel(
            name='HostessTagRelationship',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='TagGroup',
        ),
    ]
