# Generated by Django 3.0.5 on 2020-04-29 06:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20200426_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinePayTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('transaction_id', models.IntegerField(db_index=True, verbose_name='transaction_id')),
                ('access_token', models.CharField(max_length=50, verbose_name='access_token')),
                ('url', models.URLField(max_length=1024, verbose_name='url')),
                ('canceled', models.BooleanField(default=False, verbose_name='canceled')),
                ('return_code', models.CharField(max_length=10, verbose_name='return_code')),
                ('return_message', models.CharField(max_length=100, verbose_name='return_message')),
                ('amount', models.IntegerField(default=1, verbose_name='amount')),
                ('currency', models.CharField(default='JPY', max_length=10, verbose_name='currency')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Reservation')),
            ],
            options={
                'unique_together': {('reservation', 'canceled')},
            },
        ),
    ]
