# Generated by Django 3.0.5 on 2020-07-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20200711_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoommeeting',
            name='context',
            field=models.TextField(default='', verbose_name='context'),
        ),
    ]
