# Generated by Django 3.0.5 on 2020-04-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_linepaytransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linepaytransaction',
            name='transaction_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='transaction_id'),
        ),
    ]
