# Generated by Django 3.0.5 on 2020-08-15 06:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_zoommeeting_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('api_key', models.CharField(max_length=50, unique=True, verbose_name='api_key')),
                ('api_secret', models.CharField(max_length=100, verbose_name='api_secret')),
                ('api_imchat_history_token', models.CharField(max_length=500, verbose_name='api_imchat_history_token')),
                ('admin_email', models.CharField(max_length=200, verbose_name='admin_email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.ZoomAccount'),
        ),
    ]
