# Generated by Django 3.0.5 on 2020-04-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20200429_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='linepaytransaction',
            name='confirmed',
            field=models.BooleanField(default=None, null=True, verbose_name='confirmed'),
        ),
        migrations.AlterField(
            model_name='linepaytransaction',
            name='canceled',
            field=models.BooleanField(default=None, null=True, verbose_name='canceled'),
        ),
    ]
