# Generated by Django 3.0.5 on 2020-04-29 08:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20200429_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('meeting_id', models.CharField(db_index=True, max_length=100, verbose_name='meeting_id')),
                ('join_url', models.URLField(max_length=1024, verbose_name='join_url')),
                ('start_url', models.URLField(max_length=1024, verbose_name='start_url')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.Reservation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
