# Generated by Django 3.0.5 on 2020-08-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20200815_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoommeeting',
            name='end_at',
            field=models.DateTimeField(db_index=True, default=None, null=True, verbose_name='end_at'),
        ),
        migrations.AddField(
            model_name='zoommeeting',
            name='start_at',
            field=models.DateTimeField(db_index=True, default=None, null=True, verbose_name='start_at'),
        ),
    ]
