# Generated by Django 3.0.5 on 2020-08-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20200818_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoommeeting',
            name='password',
            field=models.CharField(default='', max_length=20, verbose_name='password'),
        ),
    ]
