# Generated by Django 3.0.5 on 2020-08-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_zoommeeting_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoommeeting',
            name='zoom_meeting_id',
            field=models.IntegerField(default=None, null=True, verbose_name='zoom_meeting_id'),
        ),
        migrations.AlterField(
            model_name='zoommeeting',
            name='password',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='password'),
        ),
    ]
