# Generated by Django 3.0.5 on 2020-08-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_auto_20200818_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoommeeting',
            name='zoom_meeting_id',
            field=models.CharField(default=None, max_length=20, null=True, verbose_name='zoom_meeting_id'),
        ),
    ]
