# Generated by Django 3.0.5 on 2020-08-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_auto_20200818_2320'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='linepaytransaction',
            unique_together={('reservation', 'confirmed')},
        ),
    ]
