# Generated by Django 3.0.5 on 2020-08-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_auto_20200829_1917'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='linepaytransaction',
            unique_together=set(),
        ),
    ]
