# Generated by Django 3.0.5 on 2020-05-02 12:23

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('available_id', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='available_id')),
                ('start_at', models.DateTimeField(db_index=True, editable=False, verbose_name='start_at')),
                ('end_at', models.DateTimeField(db_index=True, editable=False, verbose_name='end_at')),
            ],
        ),
    ]
